### ISSUE TITLE
Codec javascript files do not export functions

### ISSUE THREAD

**Issue by LauraDamianTNA** [TheThingsNetwork/lorawan-devices#177]
#### Summary
Hi,
We would like to use your decoder functions in another node.js open source project.
To do this, we'd need to import the modules, but we have seen that there are no exports in the codec js files.  
There is a note in the documentation:
"For security, the runtime does not support modules, require syntax, or any input/output other than defined below."
Why is there a security risk if you export the functions? Could you revise this policy so that we can reuse your code?

#### Why do we need this?
We need exports in the vendor codec js files so that we can import them in our project.

#### What is already there? What do you see now?
Javascript files without exports.

#### What is missing? What do you want to see?
I would like an export added at the end of each codec file in the vendor folder:
https://github.com/TheThingsNetwork/lorawan-devices/blob/master/vendor

module.exports = {decodeUplink};

#### How do you propose to implement this?
Add the line above.

#### Can you do this yourself and submit a Pull Request?
Yes, if you confirm that we are allowed to do it.

...
Thanks,
Laura

**Comment by nejraselimovic** [comment]
@neoaggelos can you please elaborate on the security risks mentioned above?

**Comment by neoaggelos** [comment]
Apologies for missing this one and replying late.

There at two issues here:

> > "For security, the runtime does not support modules, require syntax, or any input/output other than defined below."
> Why is there a security risk if you export the functions? Could you revise this policy so that we can reuse your code?

The security risk is not about exporting said functions, but rather to enforce that executing them in a sandbox environment will work as expected, and without producing undesirable side-effects.

> We would like to use **your** decoder functions in another node.js open source project.

The decoder functions are maintained by the device vendors themselves, so in principle this should be easy to enforce but ultimately relies upon the vendors to do this (both for existing decoders, as well as new ones that are added in the future).

**However**, note that the decoders in this repository are intended for specific use, and are not generic Javascript code. As such, adding a `module.exports = {decodeUplink}` line (which I understand to be NodeJS specific) in any of the decoders breaks them with the following error:

```
ReferenceError: module is not defined at <eval>:14:1(3)
```

If such a change is required for the needs of your project, then you will need to figure out a different way of using the decoder files from this repository.

Hope this clears out any confusion. Closing the issue since doing what is being suggested is not possible. Please re-open if you have any other questions.
