### ISSUE TITLE
sensative strips payload decoder, size too big

### ISSUE THREAD

**Issue by frahlg** [TheThingsNetwork/lorawan-devices#234]
#### Summary
The payload decoder for the sensative strips is too big. 

https://github.com/TheThingsNetwork/lorawan-devices/blob/master/vendor/sensative/strips.js

...

#### What do you see now?

https://github.com/TheThingsNetwork/lorawan-devices/blob/master/vendor/sensative/strips.js

        "namespace": "pkg/applicationserver",
        "name": "formatter_script_too_large",
        "message_format": "formatter script size exceeds maximum allowed size",
        "attributes": {
          "max_size": 4096,
          "size": 7663

#### What do you want to see instead?

Is it possible to extend the max size of the payload decoder?

#### Can you do this yourself and submit a Pull Request?

I could cut out some functionality of the strip, but then it would not work for all different configurations. My suggestion is that maybe the max size could be increased.

**Comment by nejraselimovic** [comment]
@frahlg thank you for filing this! I believe this is issue is already known: https://github.com/TheThingsNetwork/lorawan-stack/issues/4278. There is an ongoing discussion there about this problem and we are in process of resolving it (you can track the progress in that issue). I'm going to close this issue for now because it's basically a duplicate, but please feel free to reopen it if your problem still persists even after the aforementioned fix is implemented.
