### ISSUE TITLE
Issue with installing yaml validation

### ISSUE THREAD

**Issue by laurensslats** [TheThingsNetwork/lorawan-devices#6]
#### Summary
Yaml validation doesn't work and poses error messages. Seems a step is missing.

#### What do you see now?

Executed steps:
1. Update node & npm
node -v: v12.16.3
npm -v: 6.14.6
2. Install dependencies `$ npm install`
3. Validate models `$ npm run validate`
4. Add yaml.schemas in `settings.json`. Tried to set the script in both `Library/Application\ Support/Code/User/settings.json` 
& `~.vscode/settings.json `

Error message received:
```
[Error - 3:42:28 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: workspaceFolders is not iterable
  Code: -32603 
```

#### What do you want to see instead?
![image](https://user-images.githubusercontent.com/17290639/87435496-1a27ef80-c5ec-11ea-9367-30ef56d5d2d4.png)

#### How do you propose to implement this?
Need pointers from @johanstokking so I can update the documentation.

#### Can you do this yourself and submit a Pull Request?
Yes, with some pointers from Johan.

**Comment by johanstokking** [comment]
Where do you see that error?

Do you have the `lorawan-devices` folder open in VS Code or did you add it to a workspace? Because the latter doesn't work, that seems to be a limitation with VS Code workspaces and the YAML validator.

Which YAML plugin are you using? It should be `redhat.vscode-yaml`. I have `v0.8.0` installed.
