### ISSUE TITLE
Volley Boast product images not showing properly 

### ISSUE THREAD

**Issue by mvujovic-vb** [TheThingsNetwork/lorawan-devices#729]
#### Summary

In the Things Stack Cloud when doing "Register End Device" and looking up our device in the device repository, VolleyBoast product images are not showing properly. We have noticed also that the image format was changed from JPG to PNG in the merging process.

#### What do you see now?

Below is the screenshot of the page where the image is not displayed.
![Screenshot 2023-12-21 at 1 18 21 PM](https://github.com/TheThingsNetwork/lorawan-devices/assets/146228611/f03b5154-b2d2-4ae7-840b-8f585ba89011)

#### What do you want to see instead?

We want to see an image of the device as it is on: https://github.com/TheThingsNetwork/lorawan-devices/blob/master/vendor/volley-boast/vobo-hl-1.png

#### Can you do this yourself and submit a Pull Request?

No

**Comment by LDannijs** [comment]
Hello @mvujovic-vb ,
I am pretty sure this problem is caused by the PR that changed those images fell outside of the merge deadline of the current version of the stack (v3.28.2). When the next version of the Stack comes out (which is scheduled for end of January/Begin of February) it should show up properly.

**Comment by LDannijs** [comment]
v3.29.0 has fixed this issue.
